services:
  api:
    build:
      context: api
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=grupo2
      - POSTGRES_PASSWORD=derivadores2025#
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - app-network

  dashboard:
    build:
      context: dashboard
    ports:
      - "8050:8050"
    environment:
      - POSTGRES_USER=grupo2
      - POSTGRES_PASSWORD=derivadores2025#
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
      - api
    networks:
      - app-network

  db:
    build:
      context: .
    environment:
      - POSTGRES_USER=grupo2
      - POSTGRES_PASSWORD=derivadores2025#
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge